### ISSUE TITLE
Optionally add elements dynamically

### ISSUE THREAD

**Issue by midzer** [rqrauhvmra/Tobi#1]
Hi,
I've forked this awesome lightbox and extended it to introduce dynamic adding of elements.

Would be happy to open up a PR and talk about implementation details if you're interested.

Cheers
midzer

**Comment by rqrauhvmra** [comment]
Hi!

Sorry for the delayed response, too much work. Any improvement of this lightbox is welcome :)

**Comment by midzer** [comment]
Can be closed due https://github.com/rqrauhvmra/Tobi/pull/2
