### ISSUE TITLE
Missing support for '.jpeg' images.

### ISSUE THREAD

**Issue by wongjn** [rqrauhvmra/Tobi#13]
Default support `image` checker should have this in `href` regex to support `.jpeg`s:

```
/\.(png|jpe?g|tiff|tif|gif|bmp|webp|svg|ico)$/
```

**Comment by midzer** [comment]
This is a valid point. You mind submitting a PR @wongjn ?

Cheers
midzer

**Comment by rqrauhvmra** [comment]
Can be closed due #15
