### ISSUE TITLE
Code Splitting / Rewrite in ES6

### ISSUE THREAD

**Issue by rqrauhvmra** [rqrauhvmra/Tobi#21]
Hello everyone,

a small discussion about splitting Tobi into small, clear files. As part of this, I would also start writing Tobi in ES6 (The user can still use a minified, cross-browser compatible file).

Questions are:
- Files? Which parts will be there? (`tobi.js`, `drag.js`, `slide.js` ...)
- Build process? I'm not a friend of unnecessary libraries. I would like to use only ES6 and [ES6 modules](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/import) but what about [webpack modules](https://webpack.js.org/concepts/modules/), [node.js modules](https://nodejs.org/api/modules.html#modules_require) ... what are your opinions and why?

**Comment by nassimbenkirane** [comment]
Quoting this article on medium :
https://medium.com/jsdownunder/rollup-vs-webpack-javascript-bundling-in-2018-b35758a2268

In recent history, the conventional wisdom has been:

>Use webpack for apps, and Rollup for libraries

**Comment by rqrauhvmra** [comment]
Hi @nassimbenkirane,

thank you for your comment. [rollup.js](https://rollupjs.org/guide/en) sound good:

> Rollup is a module bundler for JavaScript which compiles small pieces of code into something larger and more complex, such as a library or application. It uses the new standardized format for code modules included in the ES6 revision of JavaScript, instead of previous idiosyncratic solutions such as CommonJS and AMD. ES6 modules let you freely and seamlessly combine the most useful individual functions from your favorite libraries. This will eventually be possible natively, but Rollup lets you do it today.

I'll take a look at it 👏

**Comment by midzer** [comment]
Although I'm somewhat familiar with webpack, I would love to see rollup as a bundler for this project after reading the medium article.

As Tobi constantly grows (in a good way) and ES6 is the future, splitting code in several files definetly makes sense to me.

Once v1.8 is shipped and stable, lets do this in a separate branch. I should have time in the upcoming weeks on this project, incase noone else wants to set this up initially.

**Comment by rqrauhvmra** [comment]
Hi @midzer, sounds great! I plan to release version 1.8.0 on friday and create a new branch for this issue.

I would move the files (and the upcoming converted and minified files) to a new `dist` folder and put the new several files in the `js` folder. Which files would be useful?

- tobi.js
- drag.js
- ...

**Comment by viliusle** [comment]
I have some experience in webpack, but nothing about rollup, i guess most people - same. So webpack would be easier to setup, but once its setup, we can use commands like `npm run dev`, `npm run live`to build for dev, live. 

About files structure:

- license.md
- readme.md
- .gitignore
- package.json
- package-lock.json
- dist/
- src/
  - css/
  - js/
    - main.js
      - elements/
        - image.js
        - html.js
        - iframe.js
        - video.js
        - youtube.js
      - plugins/ (for something like drag.js, maybe zoom.js, download.js, effects.js etc...)

**Comment by rqrauhvmra** [comment]
Hi @viliusle,

so far I would prefer [rollup.js](https://rollupjs.org/guide/en). It is simple and uses the new standardized format for code modules included in the ES6 revision of JavaScript. I know [webpack](https://webpack.js.org/) also support the ES2015 import statement but I think it would be too oversized for this library. With rollup.js and [rollup-plugin-babel](https://rollupjs.org/guide/en#babel) I've everything I need.

Your suggestion for the file structure looks good. I would prepare the following in the new branch:

- LICENSE.md
- README.md
- .gitignore
- package.json
- demo/
  - demo.html
- dist/
  - css/
    - tobi.css
    - tobi.min.css
  - js/
    - tobi.js
    - tobi.min.js
- src/
  - scss/
    - _functions.scss
    - _variables.scss
    - tobi.scss
  - js/
    - tobi.js
    - guestures.js
    - ... (download.js, fullscreen.js, share.js, thumb.js ... all future features)
    - media types/
      - image.js
      - html.js
      - iframe.js
      - video.js
      - youtube.js

**Comment by rqrauhvmra** [comment]
So, I'm developing this in a separate, currently private repository. More information soon.
