### ISSUE TITLE
right mouse click

### ISSUE THREAD

**Issue by viliusle** [rqrauhvmra/Tobi#24]
about: using right mouse click, image enters into drag state. Bug.
Reproduce:

1. click image to load it in modal window.
2. do right click, for example: right click + copy image address
3. moving mouse will also move image. At this point right mouse click was already released, mouse drag was not used at all.

--------
Tobi - 1.8.0
OS: mac
Browser: chrome 71

**Comment by midzer** [comment]
I can confirm this bug

**Comment by rqrauhvmra** [comment]
Hey @viliusle and @midzer,

I can't reproduce this bug for Tobi 1.8.0 in Firefox 64.0.2, Chrome 71.0.3578.98, Edge 44.17763.1.0 and IE 11.253.17763.0.

Which version do you use and in which browser does the error occur?

**Comment by rqrauhvmra** [comment]
Thank you for your answer @viliusle. I will get access to a Mac and test it there.

**Comment by midzer** [comment]
Just tested in Firefox 60 ESR and it's working fine.
Bug appears for me only in Chromium 72 (linux)
So this seams browser related^^

**Comment by rqrauhvmra** [comment]
Hmm... [Chrome works for me](https://rqrauhvmra.com/tobi/rmc-bug.mp4).

**Comment by viliusle** [comment]
No problems on windows, so only chrome on mac/linux.
