### ISSUE TITLE
Possibility to group

### ISSUE THREAD

**Issue by midzer** [rqrauhvmra/Tobi#27]
Hi all,

I've seen this issue already in `README.md` 2DO section. Until now I did not realize what it is about. Now, I have a possible case where it might come handy:

You click on a single preview image/link and Tobi opens and shows first image of a (grouped) collection. This would be really awesome for galleries for example where you don't want to put a preview image of each image inside.

Here you can discuss this feature and give ideas about how to implement it. I have time to work on it, too.

**Comment by viliusle** [comment]
I dont miss grouping feature yet, grouping already works by default, you click once and use keyboard to navigate through all images. And adding class lightbox to each image is not hard.

Button to gallery can also be created, it needs some JS like tobi.open();

There is also ability to have several groups, that are not related, but here you also have to use JS and initialise tobi with different selectors.

Some ideas: (low priority)

- Maybe using something like data-group="" inside HTML would be useful, you wont need to write additional JS. 
- creating link to already existing gallery of 3 images, will  initialise gallery with 4 items (3 + 1 duplicate.)

**Comment by rqrauhvmra** [comment]
Added grouping for 1.8.2 (#37) .
