### ISSUE TITLE
captions as HTML

### ISSUE THREAD

**Issue by dmnkhhn** [rqrauhvmra/Tobi#29]
Hello there!

I have patched Tobi to optionally use `innerHTML` instead of  `textContent` to render the caption (by setting the option `captionAsHtml` to _true_ or _false_). 
This allows the use of linebreaks and other things in the caption for a greater flexibility. 

Is this something you are interested in and that is pull request worthy?

**Comment by rqrauhvmra** [comment]
Hi @dmnkhhn,

where does the caption come from if you set `captionAsHtml`? HTML in, for example, the `alt`-Tag don't make sense. 

The idea itself is not bad.

However, PRs are always welcome. Send one. I have a look at it.
