### ISSUE TITLE
ability to change iframe size

### ISSUE THREAD

**Issue by viliusle** [rqrauhvmra/Tobi#30]
i am missing ability to change external iframe width and height for specific links only.

Solution below:

```
<a href="https://www.wikipedia.org" data-type="iframe" class="lightbox" data-height="100">
  Open Wikipedia
</a>
```

Implementation:

find:
`iframe.setAttribute('data-src', href)`
add below:
```
if(el.getAttribute('data-width'))
	iframe.style.width = el.getAttribute('data-width') + 'px';
if(el.getAttribute('data-height'))
	iframe.style.height = el.getAttribute('data-height') + 'px';
```

p.s. let me know if there is already a way to do it.

**Comment by rqrauhvmra** [comment]
Hey @viliusle,

Sorry for the late reply. I would integrate it in the next version.

Thanks for your feedback.
