### ISSUE TITLE
Emit events on state changes

### ISSUE THREAD

**Issue by danielpost** [rqrauhvmra/Tobi#33]
Tobi currently exposes a few methods (`open`, `add` etc). It might be helpful to additionally emit events during some of these state changes (similar to [tiny-slider](https://github.com/ganlanyuan/tiny-slider#custom-events)), which would allow users to run a callback without running any methods.

There's a change this functionality is already available and I just missed it, in which case please feel free to let me know and close this.

**Comment by rqrauhvmra** [comment]
Hey @danielpost ,

No. Tobi doesn't currently have something like that but it could be very useful.

Thanks for your feedback.

**Comment by rqrauhvmra** [comment]
Will be implemented in Tobii (version 2.x.x)
