### ISSUE TITLE
iframe scrolling on ios [mobile safari] devices

### ISSUE THREAD

**Issue by coldes** [rqrauhvmra/Tobi#34]
...fyi, in order for an external website to scroll when Tobi is viewed on ios [safari] - eg iframe demo loading _Wikipedia_, the following needs to be added to tobi css
```
/* Lightbox */
.tobi { ...
overflow-y: auto;
-webkit-overflow-scrolling: touch;
-webkit-transform: translate3d(0,0,0);
}

**Comment by rqrauhvmra** [comment]
Hey @coldes,

thanks for your feedback. Can you explain or do you have a resource why this is necessary? I don't have access to an iOS device.

**Comment by coldes** [comment]
...fyi
https://davidwalsh.name/scroll-iframes-ios
