### ISSUE TITLE
Option to not preload youtube videos?

### ISSUE THREAD

**Issue by Gerben321** [rqrauhvmra/Tobi#38]
Hi there,

Trying out your great little lightbox, and it was easy to set up and in use. However when I watch my network toolbar I see there's a lot of data being loaded as soon as I create the Tobi object in JS. Instead of a 400kb page my page is now 12mb without showing a single video yet.

Is this some kind of option I can disable that I missed? Would be great when it loads a video as soon as it is requested. ;)

**Comment by rqrauhvmra** [comment]
Hi @Gerben321,

which version of Tobi do you use? In which browser does the behavior occur? [In this example on CodePen](https://s.codepen.io/rqrauhvmra/debug/rgpjXE/LDMmdPvPwPwk) only a few scripts for the IFrame player API load.

**Comment by Gerben321** [comment]
The most current (not 2.0 yet) release. Used Firefox and Chrome. Can't check your link, it expired. It does happen in other YouTube examples I've found.

**Comment by rqrauhvmra** [comment]
Hey @Gerben321,

please provide an example where the error occurs. On CodePen for example.
