### ISSUE TITLE
closing by default

### ISSUE THREAD

**Issue by viliusle** [rqrauhvmra/Tobi#4]
i believe that setting below should be set by default:
`docClose: true`

**Comment by rqrauhvmra** [comment]
Hi @viliusle 

You're right. I do not use it but I also have more and more customers who want it. I will change it after my vacation next week.

**Comment by midzer** [comment]
I support this one.

**Comment by midzer** [comment]
Can do this little PR once we got dev branched production ready and merged into master

**Comment by rqrauhvmra** [comment]
Sounds great @midzer 

in my dev branch I also changed the README.md in this regard.

**Comment by rqrauhvmra** [comment]
Can be closed due #6
