### ISSUE TITLE
Images with Query Strings

### ISSUE THREAD

**Issue by HashandSalt** [rqrauhvmra/Tobi#41]
Great plugin, but does not seem to like images that have a query string on the end. In my case I was using images from Shopify CDN.

**Comment by midzer** [comment]
Thanks for filling @HashandSalt 

I haven't tested images with a query string yet. Right now we check support for images via https://github.com/rqrauhvmra/Tobi/blob/18268f4f8a6d7d1bc6b012ab21dd906689ff8189/js/tobi.js#L124

**Comment by rqrauhvmra** [comment]
Hey @HashandSalt,

you're right. I'll correct that.
