### ISSUE TITLE
data-type, lowercase and uppercase image-types

### ISSUE THREAD

**Issue by builtbymax** [rqrauhvmra/Tobi#45]
Hey!

When using the library I noticed that images with a data-type in uppercase are not displayed. As an example:

image.**jpg** = works
image.**JPG** = does _not_ work

The lightbox opens, but the image cannot be displayed. After that a JavaScript error occurs when closing the lightbox: 

"_Uncaught TypeError: Cannot read property 'querySelector' of undefined_"

With some research I found out that in **`line 124`** the RegEx definition does not work in "case insensitive mode". Here "/i" is missing for a correct execution or does this lead to another problem and was therefore not considered? 

In my opinion this would be the right approach: **(?)**

`return !el.hasAttribute('data-type') && el.href.match(/\.(png|jpe?g|tiff|tif|gif|bmp|webp|svg|ico)$/i)`

Maybe with that information, you could take a look at it.

**Comment by rqrauhvmra** [comment]
Oh, man, this was already fixed with #28 but I broke it again. Thank you for your hint @builtbymax. I will fix it.

**Comment by builtbymax** [comment]
Great you took care of it. Do you have any idea when you can merge the fix - because your library is used in one of our projects in the production system. Just for my information - **no stress** please.

**Comment by rqrauhvmra** [comment]
Hey @builtbymax, which version do you use? [Version 1.9.0](https://codepen.io/rqrauhvmra/pen/ZRZdwG) looks good (I changed 1.jpg to 1.JPG)

**Comment by builtbymax** [comment]
> Hey @builtbymax, which version do you use? [Version 1.9.0](https://codepen.io/rqrauhvmra/pen/ZRZdwG) looks good (I changed 1.jpg to 1.JPG)

Hey @rqrauhvmra
I see that the error is absolutely with me. I was on **version 1.8.1** ... 😞  - I missed you changing the NPM package and the version 1.8.1 is depracted. I changed and updated the package, now it works. Many thanks for your help and effort. Sorry for your time.

**Comment by rqrauhvmra** [comment]
No problem. I'll communicate big changes in the future better.
