### ISSUE TITLE
New Media type 'video'

### ISSUE THREAD

**Issue by midzer** [rqrauhvmra/Tobi#46]
Hi all,

right now, we can use `<video>` elements via `data-type="html"` easily.

How about we introduce a new type `video`?
We could separate all special video code, remove the extra `<div>` wrapper for them and show this feature more prominently in README.

Have a nice sunday
midzer

**Comment by rqrauhvmra** [comment]
Hi @midzer,

that's a good suggestion 👏 

Cheers,
Benjamin

**Comment by midzer** [comment]
As mentioned in respective PR, we should close this one for good
