### ISSUE TITLE
Option for (oversized) scrollable images

### ISSUE THREAD

**Issue by midzer** [rqrauhvmra/Tobi#50]
Hi,

I have a use case where I need a rather big image (for example a restaurant menu) to be vertically scrollable within the lightbox.

Right now, I somehow hacked it fast into Tobi here https://gasthaus-3rosen.de/speisekarte/ (click on "Tageskarte"). But there should be a more cleaner and better approach.

What do you think of the idea to have an optional `data-` attribute or `class` on images to allow vertical and/or horizontal scrolling?

Have a nice weekend and cheers
midzer

**Comment by rqrauhvmra** [comment]
Hi @midzer, 

I don't know, would that be a common use case? I will think about it.

**Comment by midzer** [comment]
Yeah, probably not very wide spread case. If it bloats the library, we better not implement it.

Just thinking out loud about this idea :)

**Comment by rqrauhvmra** [comment]
I'll keep it in mind for [Tobii](https://github.com/rqrauhvmra/Tobii/tree/develop).
