### ISSUE TITLE
Stop video playback when using iframe

### ISSUE THREAD

**Issue by joergsteinhauer** [rqrauhvmra/Tobi#51]
Currently, if you're using iframe-type and embed a video (e.g. youtube or vimeo), the video doesn't stop playing when you close the layer. 

In my case I wanna embed vimeo videos, so I have to use iframe-type.

Is there already an option to stop playing iframe-videos by closing the layer?

**Comment by rqrauhvmra** [comment]
Hey @joergsteinhauer,

this is currently only supported for YouTube. We will integrate support for vimeo in an upcoming version.

**Comment by rqrauhvmra** [comment]
Will be implemented in Tobii (version 2.x.x)
