### ISSUE TITLE
triggering close lightbox

### ISSUE THREAD

**Issue by txirrindulari** [rqrauhvmra/Tobi#52]
Hi,
sorry for my simple question but I do not find the right answer anywhere on internet.

How do I trigger the closing action of the lightbox with javascript in order to callback another funtion?

**Comment by rqrauhvmra** [comment]
Hi @txirrindulari,

do you mean something like that:

```js
tobi.close(function() {
   // ...
})
```

Tobi -> [API](https://github.com/rqrauhvmra/Tobi#api)

**Comment by txirrindulari** [comment]
I tried this but I get "Tobi is already closed", so funtion does not run

**Comment by rqrauhvmra** [comment]
Do you want to run this function whenever the user closes the lightbox? The one I mentioned only works with a manual call to close the lightbox.

Tobi will be able to emit events on state changes with the next version 2.

**Comment by txirrindulari** [comment]
Correct, is what I expected in operation. Capturing any closure of the light box should fire my function.
Would there be any quick trick before version 2?
I did not find it.

**Comment by rqrauhvmra** [comment]
Except writing it hard in the code (until [Tobii](https://github.com/rqrauhvmra/Tobii/tree/develop) supports it), unfortunately not.
